<?php

CarteWagon::addSqlQuery('CREER_CARTE_WAGON',
'INSERT INTO CARTE_WAGON (COULEUR, NO_PARTIE)
VALUES(: couleur, : no_partie)');
CarteWagon::addSqlQuery('DEFAUSSER',
'UPDATE CARTE_WAGON
SET NO_UTILISATEUR= NULL
WHERE EXISTS (
    SELECT NO_CARTE_WAGON
	FROM  (SELECT NO_CARTE_WAGON
                FROM CARTE_WAGON
                WHERE NO_UTILISATEUR = : no_utilisateur AND couleur=: couleur
                ORDER BY RAND()
                LIMIT : nb_cartes) AS PIOCHE
WHERE PIOCHE.NO_CARTE_WAGON = CARTE_WAGON.NO_CARTE_WAGON AND NO_PARTIE=: no_partie
)');
CarteWagon::addSqlQuery('PIOCHER',
'UPDATE CARTE_WAGON
SET NO_UTILISATEUR=: no_utilisateur
WHERE EXISTS (
    SELECT NO_CARTE_WAGON
    FROM  (SELECT NO_CARTE_WAGON
            FROM CARTE_WAGON
            WHERE NO_UTILISATEUR IS NULL
            ORDER BY RAND()
            LIMIT 2) AS PIOCHE
    WHERE PIOCHE.NO_CARTE_WAGON = CARTE_WAGON.NO_CARTE_WAGON AND NO_PARTIE=: no_partie
    );'
//SELECT @value;
);
CarteWagon::addSqlQuery('DISRIBUER',
'UPDATE CARTE_WAGON
SET NO_UTILISATEUR=: no_utilisateur
WHERE EXISTS (
    SELECT NO_CARTE_WAGON
	FROM  (SELECT NO_CARTE_WAGON
                FROM CARTE_WAGON
                WHERE NO_UTILISATEUR IS NULL
                ORDER BY RAND()
                LIMIT 4) AS PIOCHE
WHERE PIOCHE.NO_CARTE_WAGON = CARTE_WAGON.NO_CARTE_WAGON AND NO_PARTIE=: no_partie
)');
CarteWagon::addSqlQuery('NB_CARTES_WAGONS',
"SELECT (SELECT COUNT(NO_UTILISATEUR)
        FROM CARTE_WAGON
        WHERE NO_UTILISATEUR=: no_utilisateur AND COULEUR='noir') AS NB_CARTES_NOIRES ,
        
        (SELECT COUNT(NO_UTILISATEUR)
        FROM CARTE_WAGON
        WHERE NO_UTILISATEUR=: no_utilisateur AND COULEUR='blanc')  AS NB_CARTES_BLANCHES,
        
        (SELECT COUNT(NO_UTILISATEUR)
        FROM CARTE_WAGON
        WHERE NO_UTILISATEUR=: no_utilisateur AND COULEUR='rose' ) AS NB_CARTES_ROSES ,

        (SELECT COUNT(NO_UTILISATEUR)
        FROM CARTE_WAGON
        WHERE NO_UTILISATEUR=: no_utilisateur AND COULEUR='orange') AS NB_CARTES_ORANGES ,

        (SELECT COUNT(NO_UTILISATEUR)
        FROM CARTE_WAGON
        WHERE NO_UTILISATEUR=: no_utilisateur AND COULEUR='rouge') AS NB_CARTES_ROUGES,

        (SELECT COUNT(NO_UTILISATEUR)
        FROM CARTE_WAGON
        WHERE NO_UTILISATEUR=: no_utilisateur AND COULEUR='bleu') AS NB_CARTES_BLEUES,

        (SELECT COUNT(NO_UTILISATEUR)
        FROM CARTE_WAGON
        WHERE NO_UTILISATEUR=: no_utilisateur AND COULEUR='vert') AS NB_CARTES_VERTES,

        (SELECT COUNT(NO_UTILISATEUR)
        FROM CARTE_WAGON
        WHERE NO_UTILISATEUR=: no_utilisateur AND COULEUR='jaune') AS NB_CARTES_JAUNES,

        (SELECT COUNT(NO_UTILISATEUR)
        FROM CARTE_WAGON
        WHERE NO_UTILISATEUR=: no_utilisateur AND COULEUR='locomotive') AS NB_CARTES_LOCOMOTIVES"
);

?>