<?php

CarteDestination::addSqlQuery('CREER_CARTE_DESTINATION',
'INSERT INTO CARTE_DESTINATION (DESTINATION, NO_PARTIE)
VALUES(: destination, : no_partie)');
CarteDestination::addSqlQuery('DEFAUSSER_CARTE_DESTINATION',
'UPDATE CARTE_DESTINATION
SET NO_UTILISATEUR= NULL
WHERE DESTINATION = : destination AND NO_PARTIE=: no_partie
)');
CarteDestination::addSqlQuery('PIOCHER_CARTE_DESTINATION',
'UPDATE CARTE_DESTINATION
SET NO_UTILISATEUR=: no_utilisateur
WHERE EXISTS (
    SELECT DESTINATION
	FROM  (SELECT DESTINATION
			FROM CARTE_DESTINATION
			WHERE NO_UTILISATEUR IS NULL
			ORDER BY RAND()
			LIMIT 1) AS PIOCHE
WHERE PIOCHE.DESTINATION = CARTE_DESTINATION.DESTINATION AND NO_PARTIE=: no_partie
)');
CarteDestination::addSqlQuery('DISRIBUER_CARTE_DESTINATION',
'UPDATE CARTE_DESTINATION
SET NO_UTILISATEUR=: no_utilisateur
WHERE EXISTS (
    SELECT DESTINATION
	FROM  (SELECT DESTINATION
			FROM CARTE_DESTINATION
			WHERE NO_UTILISATEUR IS NULL
			ORDER BY RAND()
			LIMIT 3) AS PIOCHE
WHERE PIOCHE.DESTINATION = CARTE_DESTINATION.DESTINATION AND NO_PARTIE=: no_partie
)');
?>