<?php

Coup::addSqlQuery('CREER_COUP',
'INSERT INTO COUP (CHEMIN, NO_PARTIE)
VALUES(: chemin, : no_partie)');
Coup::addSqlQuery('ATTRIBUER_COUP',
'UPDATE COUP SET NO_UTILISATEUR=: no_utilisateur
WHERE CHEMIN=: chemin AND NO_PARTIE=: no_partie');
Coup::addSqlQuery('COUPS_JOUES',
'SELECT CHEMIN,COULEUR_WAGONS
FROM COUP,JOUEUR
WHERE COUP.NO_UTILISATEUR IS NOT NULL AND JOUEUR.NO_UTILISATEUR = COUP.NO_UTILISATEUR AND COUP.NO_PARTIE=: no_partie');
?>
