<?php
	
User::addSqlQuery('LISTE_LOGINS',
'SELECT LOGIN FROM UTILISATEUR');
User::addSqlQuery('USER_LIST',
'SELECT * FROM UTILISATEUR ORDER BY LOGIN');
User::addSqlQuery('CLASSEMENT',
'SELECT LOGIN, VICTOIRES, IF(NB_PARTIES = 0,0,VICTOIRES/NB_PARTIES ) AS RATIO,NB_PARTIES, SCORE_TOTAL FROM UTILISATEUR ORDER BY VICTOIRES DESC'); 
User::addSqlQuery('INFOS_USER',
'SELECT * FROM UTILISATEUR WHERE NO_UTILISATEUR=: no_utilisateur');
User::addSqlQuery('CREER_USER',
'INSERT INTO UTILISATEUR (LOGIN, PASSWORD, MAIL, NOM, PRENOM, DATE_DE_NAISSANCE, SEXE, PAYS)
VALUES(: login, : password, : mail, : nom, : prenom, : date_de_naissance, : sexe, : pays)');
User::addSqlQuery('TRY_LOGIN',
'SELECT NO_UTILISATEUR FROM UTILISATEUR WHERE LOGIN=: login AND PASSWORD=: password');
User::addSqlQuery('UPDATE_PROFILE',
'UPDATE UTILISATEUR SET NOM=: nom, PRENOM=: prenom, MAIL=: mail, PAYS=: pays WHERE NO_UTILISATEUR=: no_utilisateur');
User::addSqlQuery('UPDATE_PASSWORD',
'UPDATE UTILISATEUR SET PASSWORD=: password WHERE NO_UTILISATEUR=: no_utilisateur');

?>